using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Glacier.Chrono.Generator;

[Generator]
public class ChronoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Filter for structs decorated with [ChronoTable]
        IncrementalValuesProvider<StructDeclarationSyntax> structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)!;

        // 2. Combine with Compilation to get semantic symbols
        IncrementalValueProvider<(Compilation, System.Collections.Immutable.ImmutableArray<StructDeclarationSyntax>)> compilationAndStructs =
            context.CompilationProvider.Combine(structDeclarations.Collect());

        // 3. Register source output
        context.RegisterSourceOutput(compilationAndStructs,
            static (spc, source) => Execute(source.Item1, source.Item2, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is StructDeclarationSyntax structDecl && structDecl.AttributeLists.Count > 0;
    }

    private static StructDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var structDecl = (StructDeclarationSyntax)context.Node;
        foreach (var attributeList in structDecl.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var name = attribute.Name.ToString();
                if (name.Contains("ChronoTable"))
                {
                    return structDecl;
                }
            }
        }
        return null;
    }

    private static void Execute(Compilation compilation, System.Collections.Immutable.ImmutableArray<StructDeclarationSyntax> structs, SourceProductionContext context)
    {
        if (structs.IsDefaultOrEmpty)
            return;

        foreach (var structDecl in structs.Distinct())
        {
            var semanticModel = compilation.GetSemanticModel(structDecl.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(structDecl) is not INamedTypeSymbol structSymbol)
                continue;

            GenerateCodeForStruct(structSymbol, context);
        }
    }

    private static void GenerateCodeForStruct(INamedTypeSymbol structSymbol, SourceProductionContext context)
    {
        string structName = structSymbol.Name;
        string ns = structSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : structSymbol.ContainingNamespace.ToDisplayString();

        string? timestampField = null;
        var metrics = new List<string>();
        var categories = new List<string>();

        foreach (var member in structSymbol.GetMembers())
        {
            if (member is IFieldSymbol fieldSymbol)
            {
                foreach (var attr in fieldSymbol.GetAttributes())
                {
                    var attrName = attr.AttributeClass?.Name;
                    if (attrName == "TimestampAttribute")
                    {
                        timestampField = fieldSymbol.Name;
                    }
                    else if (attrName == "MetricAttribute")
                    {
                        metrics.Add(fieldSymbol.Name);
                    }
                    else if (attrName == "CategoryAttribute")
                    {
                        categories.Add(fieldSymbol.Name);
                    }
                }
            }
            else if (member is IPropertySymbol propSymbol)
            {
                foreach (var attr in propSymbol.GetAttributes())
                {
                    var attrName = attr.AttributeClass?.Name;
                    if (attrName == "TimestampAttribute")
                    {
                        timestampField = propSymbol.Name;
                    }
                    else if (attrName == "MetricAttribute")
                    {
                        metrics.Add(propSymbol.Name);
                    }
                    else if (attrName == "CategoryAttribute")
                    {
                        categories.Add(propSymbol.Name);
                    }
                }
            }
        }

        if (timestampField == null)
        {
            return; // Must have at least a timestamp
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers.Binary;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.IO.MemoryMappedFiles;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine("using Glacier.Chrono.Compression;");
        sb.AppendLine("using Glacier.Chrono.Storage;");
        sb.AppendLine();

        // 1. CompactorBuffers
        sb.AppendLine($"public class {structName}CompactorBuffers");
        sb.AppendLine("{");
        sb.AppendLine($"    public readonly {structName}[] RowBuffer;");
        sb.AppendLine("    public readonly long[] Timestamps;");
        foreach (var m in metrics)
            sb.AppendLine($"    public readonly float[] {m}s;");
        foreach (var c in categories)
            sb.AppendLine($"    public readonly int[] {c}s;");
        sb.AppendLine();
        sb.AppendLine("    public readonly byte[] CompressedTimestamps;");
        foreach (var m in metrics)
            sb.AppendLine($"    public readonly byte[] Compressed{m}s;");
        foreach (var c in categories)
            sb.AppendLine($"    public readonly byte[] Compressed{c}s;");
        sb.AppendLine();
        sb.AppendLine("    public readonly byte[] FileHeaderBuffer;");
        sb.AppendLine();
        sb.AppendLine($"    public {structName}CompactorBuffers(int batchSize)");
        sb.AppendLine("    {");
        sb.AppendLine($"        RowBuffer = new {structName}[batchSize];");
        sb.AppendLine("        Timestamps = new long[batchSize];");
        foreach (var m in metrics)
            sb.AppendLine($"        {m}s = new float[batchSize];");
        foreach (var c in categories)
            sb.AppendLine($"        {c}s = new int[batchSize];");
        sb.AppendLine();
        sb.AppendLine("        CompressedTimestamps = new byte[batchSize * 9 + 64];");
        foreach (var m in metrics)
            sb.AppendLine($"        Compressed{m}s = new byte[batchSize * 6 + 64];");
        foreach (var c in categories)
            sb.AppendLine($"        Compressed{c}s = new byte[batchSize * 5 + 64];");
        sb.AppendLine();
        sb.AppendLine("        FileHeaderBuffer = new byte[64];");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // 2. Compactor
        sb.AppendLine($"public static class {structName}Compactor");
        sb.AppendLine("{");
        sb.AppendLine($"    public static bool CompactBatch(");
        sb.AppendLine($"        HotRingBuffer<{structName}> ringBuffer,");
        sb.AppendLine($"        ref long nextSequenceToRead,");
        sb.AppendLine($"        int batchSize,");
        sb.AppendLine($"        string outputDirectory,");
        sb.AppendLine($"        {structName}CompactorBuffers buffers)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!ringBuffer.TryReadBatch(nextSequenceToRead, buffers.RowBuffer))");
        sb.AppendLine("        {");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        Array.Sort(buffers.RowBuffer, 0, batchSize);");
        sb.AppendLine();
        sb.AppendLine("        for (int i = 0; i < batchSize; i++)");
        sb.AppendLine("        {");
        sb.AppendLine($"            buffers.Timestamps[i] = buffers.RowBuffer[i].{timestampField};");
        foreach (var m in metrics)
            sb.AppendLine($"            buffers.{m}s[i] = buffers.RowBuffer[i].{m};");
        foreach (var c in categories)
            sb.AppendLine($"            buffers.{c}s[i] = buffers.RowBuffer[i].{c};");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        int tsLen = TimestampCompressor.Compress(buffers.Timestamps, buffers.CompressedTimestamps);");
        foreach (var m in metrics)
            sb.AppendLine($"        int {m}Len = GorillaCompressor.Compress(buffers.{m}s, buffers.Compressed{m}s);");
        foreach (var c in categories)
            sb.AppendLine($"        int {c}Len = IntegerRleCompressor.Compress(buffers.{c}s, buffers.Compressed{c}s);");
        sb.AppendLine();
        sb.AppendLine("        long tsOffset = 64;");
        
        string prevOffset = "tsOffset";
        string prevLen = "tsLen";
        foreach (var m in metrics)
        {
            sb.AppendLine($"        long {m}Offset = {prevOffset} + {prevLen};");
            prevOffset = $"{m}Offset";
            prevLen = $"{m}Len";
        }
        foreach (var c in categories)
        {
            sb.AppendLine($"        long {c}Offset = {prevOffset} + {prevLen};");
            prevOffset = $"{c}Offset";
            prevLen = $"{c}Len";
        }
        sb.AppendLine();
        sb.AppendLine("        Span<byte> header = buffers.FileHeaderBuffer;");
        sb.AppendLine("        header.Clear();");
        sb.AppendLine("        BinaryPrimitives.WriteUInt32LittleEndian(header.Slice(0, 4), 0x48434C47);");
        sb.AppendLine("        BinaryPrimitives.WriteUInt32LittleEndian(header.Slice(4, 4), 1);");
        sb.AppendLine("        BinaryPrimitives.WriteInt32LittleEndian(header.Slice(8, 4), batchSize);");
        sb.AppendLine();
        sb.AppendLine("        BinaryPrimitives.WriteInt64LittleEndian(header.Slice(12, 8), tsOffset);");
        sb.AppendLine("        BinaryPrimitives.WriteInt32LittleEndian(header.Slice(20, 4), tsLen);");
        sb.AppendLine();

        int slot = 0;
        foreach (var m in metrics)
        {
            int offsetPos = 24 + slot * 12;
            int lenPos = offsetPos + 8;
            sb.AppendLine($"        BinaryPrimitives.WriteInt64LittleEndian(header.Slice({offsetPos}, 8), {m}Offset);");
            sb.AppendLine($"        BinaryPrimitives.WriteInt32LittleEndian(header.Slice({lenPos}, 4), {m}Len);");
            slot++;
        }
        foreach (var c in categories)
        {
            int offsetPos = 24 + slot * 12;
            int lenPos = offsetPos + 8;
            sb.AppendLine($"        BinaryPrimitives.WriteInt64LittleEndian(header.Slice({offsetPos}, 8), {c}Offset);");
            sb.AppendLine($"        BinaryPrimitives.WriteInt32LittleEndian(header.Slice({lenPos}, 4), {c}Len);");
            slot++;
        }
        sb.AppendLine();
        sb.AppendLine("        Directory.CreateDirectory(outputDirectory);");
        sb.AppendLine($"        string fileName = Path.Combine(outputDirectory, $\"chunk_{{nextSequenceToRead}}.glacier\");");
        sb.AppendLine();
        sb.AppendLine("        using (var fs = new FileStream(fileName, FileMode.Create, FileAccess.Write, FileShare.None, 4096, FileOptions.WriteThrough))");
        sb.AppendLine("        {");
        sb.AppendLine("            fs.Write(header);");
        sb.AppendLine("            fs.Write(buffers.CompressedTimestamps.AsSpan(0, tsLen));");
        foreach (var m in metrics)
            sb.AppendLine($"            fs.Write(buffers.Compressed{m}s.AsSpan(0, {m}Len));");
        foreach (var c in categories)
            sb.AppendLine($"            fs.Write(buffers.Compressed{c}s.AsSpan(0, {c}Len));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        long lastReadSequence = nextSequenceToRead + batchSize - 1;");
        sb.AppendLine("        ringBuffer.CommitReadProgress(lastReadSequence);");
        sb.AppendLine("        nextSequenceToRead += batchSize;");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // 3. QueryBuffers
        sb.AppendLine($"public class {structName}QueryBuffers");
        sb.AppendLine("{");
        foreach (var m in metrics)
            sb.AppendLine($"    public readonly float[] {m}s;");
        foreach (var c in categories)
            sb.AppendLine($"    public readonly int[] {c}s;");
        foreach (var m in metrics)
            sb.AppendLine($"    public readonly byte[] Compressed{m}Buffer;");
        foreach (var c in categories)
            sb.AppendLine($"    public readonly byte[] Compressed{c}Buffer;");
        sb.AppendLine();
        sb.AppendLine($"    public {structName}QueryBuffers(int maxBatchSize)");
        sb.AppendLine("    {");
        foreach (var m in metrics)
            sb.AppendLine($"        {m}s = new float[maxBatchSize];");
        foreach (var c in categories)
            sb.AppendLine($"        {c}s = new int[maxBatchSize];");
        foreach (var m in metrics)
            sb.AppendLine($"        Compressed{m}Buffer = new byte[maxBatchSize * 6 + 64];");
        foreach (var c in categories)
            sb.AppendLine($"        Compressed{c}Buffer = new byte[maxBatchSize * 5 + 64];");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // 4. QueryEngine with specialized methods
        sb.AppendLine($"public static class {structName}QueryEngine");
        sb.AppendLine("{");
        foreach (var m in metrics)
        {
            foreach (var c in categories)
            {
                sb.AppendLine($"    public static double GetAverage{m}For{c}(string chunkFilePath, int target{c}, {structName}QueryBuffers buffers)");
                sb.AppendLine("    {");
                sb.AppendLine("        using (var mmf = MemoryMappedFile.CreateFromFile(chunkFilePath, FileMode.Open, null, 0, MemoryMappedFileAccess.Read))");
                sb.AppendLine("        {");
                sb.AppendLine("            int rowCount;");
                sb.AppendLine($"            long {m}Offset, {c}Offset;");
                sb.AppendLine($"            int {m}Len, {c}Len;");
                sb.AppendLine();
                sb.AppendLine("            using (var accessor = mmf.CreateViewAccessor(0, 64, MemoryMappedFileAccess.Read))");
                sb.AppendLine("            {");
                sb.AppendLine("                byte[] header = new byte[64];");
                sb.AppendLine("                accessor.ReadArray(0, header, 0, 64);");
                sb.AppendLine("                uint magic = BinaryPrimitives.ReadUInt32LittleEndian(header.AsSpan(0, 4));");
                sb.AppendLine("                if (magic != 0x48434C47) throw new InvalidDataException(\"Magic mismatch.\");");
                sb.AppendLine("                rowCount = BinaryPrimitives.ReadInt32LittleEndian(header.AsSpan(8, 4));");
                sb.AppendLine();
                
                int mIndex = metrics.IndexOf(m);
                int cIndex = categories.IndexOf(c) + metrics.Count;
                int mOffsetPos = 24 + mIndex * 12;
                int mLenPos = mOffsetPos + 8;
                int cOffsetPos = 24 + cIndex * 12;
                int cLenPos = cOffsetPos + 8;

                sb.AppendLine($"                {m}Offset = BinaryPrimitives.ReadInt64LittleEndian(header.AsSpan({mOffsetPos}, 8));");
                sb.AppendLine($"                {m}Len = BinaryPrimitives.ReadInt32LittleEndian(header.AsSpan({mLenPos}, 4));");
                sb.AppendLine($"                {c}Offset = BinaryPrimitives.ReadInt64LittleEndian(header.AsSpan({cOffsetPos}, 8));");
                sb.AppendLine($"                {c}Len = BinaryPrimitives.ReadInt32LittleEndian(header.AsSpan({cLenPos}, 4));");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine("            if (rowCount <= 0) return 0.0;");
                sb.AppendLine();
                sb.AppendLine($"            using (var metricAccessor = mmf.CreateViewAccessor({m}Offset, {m}Len, MemoryMappedFileAccess.Read))");
                sb.AppendLine("            {");
                sb.AppendLine($"                metricAccessor.ReadArray(0, buffers.Compressed{m}Buffer, 0, {m}Len);");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine($"            using (var catAccessor = mmf.CreateViewAccessor({c}Offset, {c}Len, MemoryMappedFileAccess.Read))");
                sb.AppendLine("            {");
                sb.AppendLine($"                catAccessor.ReadArray(0, buffers.Compressed{c}Buffer, 0, {c}Len);");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine($"            Span<float> metricSpan = buffers.{m}s.AsSpan(0, rowCount);");
                sb.AppendLine($"            Span<int> catSpan = buffers.{c}s.AsSpan(0, rowCount);");
                sb.AppendLine();
                sb.AppendLine($"            GorillaCompressor.Decompress(buffers.Compressed{m}Buffer.AsSpan(0, {m}Len), metricSpan);");
                sb.AppendLine($"            IntegerRleCompressor.Decompress(buffers.Compressed{c}Buffer.AsSpan(0, {c}Len), catSpan);");
                sb.AppendLine();
                sb.AppendLine("            double sum = 0.0;");
                sb.AppendLine("            int count = 0;");
                sb.AppendLine("            int simdLength = Vector<float>.Count;");
                sb.AppendLine("            int i = 0;");
                sb.AppendLine();
                sb.AppendLine("            if (Vector.IsHardwareAccelerated && rowCount >= simdLength)");
                sb.AppendLine("            {");
                sb.AppendLine($"                var targetVec = new Vector<int>(target{c});");
                sb.AppendLine("                var zeroVec = Vector<float>.Zero;");
                sb.AppendLine("                var oneIntVec = Vector<int>.One;");
                sb.AppendLine("                var zeroIntVec = Vector<int>.Zero;");
                sb.AppendLine("                var sumAccumulator = Vector<float>.Zero;");
                sb.AppendLine("                var countAccumulator = Vector<int>.Zero;");
                sb.AppendLine();
                sb.AppendLine("                for (; i <= rowCount - simdLength; i += simdLength)");
                sb.AppendLine("                {");
                sb.AppendLine("                    var catVec = new Vector<int>(catSpan.Slice(i, simdLength));");
                sb.AppendLine("                    var metricVec = new Vector<float>(metricSpan.Slice(i, simdLength));");
                sb.AppendLine("                    Vector<int> maskInt = Vector.Equals(catVec, targetVec);");
                sb.AppendLine("                    Vector<float> maskFloat = Vector.AsVectorSingle(maskInt);");
                sb.AppendLine("                    sumAccumulator += Vector.ConditionalSelect(maskFloat, metricVec, zeroVec);");
                sb.AppendLine("                    countAccumulator += Vector.ConditionalSelect(maskInt, oneIntVec, zeroIntVec);");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.AppendLine("                for (int j = 0; j < simdLength; j++)");
                sb.AppendLine("                {");
                sb.AppendLine("                    sum += sumAccumulator[j];");
                sb.AppendLine("                    count += countAccumulator[j];");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine("            for (; i < rowCount; i++)");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (catSpan[i] == target{c})");
                sb.AppendLine("                {");
                sb.AppendLine("                    sum += metricSpan[i];");
                sb.AppendLine("                    count++;");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine("            return count == 0 ? 0.0 : sum / count;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }
        }
        sb.AppendLine("}");

        context.AddSource($"{structName}_Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
